# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  TargetRubyVersion: 3.4
  TargetRailsVersion: 8.1
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'vendor/**/*'

# Overwrite or add rules to create your own house style
Style/StringLiterals:
  EnforcedStyle: single_quotes

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space
